### ISSUE TITLE
Unable to run a simple example

### ISSUE THREAD

**Issue by CaspianA1** [BitPuffin/sexpresso#4]
Here is my code:

```c++
#define SEXPRESSO_OPT_OUT_PIKESTYLE
#ifdef SEXPRESSO_OPT_OUT_PIKESTYLE
#ifndef SEXPRESSO_HEADER
#define SEXPRESSO_HEADER
#include <vector>
#include <string>
#include <cstdint>
#include "../sexpresso/sexpresso/sexpresso.hpp"
#endif
#endif

int main() {
    std::string expression = " ( define x 5 ) ";
    auto parsetree = sexpresso::parse(expression);
}
```

Running this
```bash
g++ -std=c++11 example_1.cpp
```
Causes this error:
```bash
Undefined symbols for architecture x86_64:
  "sexpresso::parse(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      _main in example_1-5608e3.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
I have no idea why this is happening. If you know why, please let me know.

**Comment by BitPuffin** [comment]
Hey, thanks for checking out the project.

Sorry for being late in getting back to you.

The reason why it doesn't work appears to be because you're not compiling sexpresso with your project (or linking to the library). Try doing that and see if it runs!

I have been pondering about whether or not it would be better to turn sexpresso into a header only library to make it easier to just drop into a project and use.

**Comment by CaspianA1** [comment]
Thanks; I'll try that. I agree - making it header-only would make it more convenient to use.

**Comment by BitPuffin** [comment]
I'll open a separate issue for that.

Re-open the issue if you still have trouble! Thanks
